# Generated by Django 5.2.8 on 2025-12-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='google_map_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
